version: "3.8"
services:
  www:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
    env_file:
      - .env
    networks:
      - mongo-network
    depends_on:
      - mongodb

  mongodb:
    restart: unless-stopped
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017

    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
